"""What counts as normal, and for whom.

Two kinds of reference data live here:

  ANCHORS      measured fake-vs-organic account cohorts from the StarScout
               dataset (corpus/calibration.json). These describe ALL-TIME
               stargazer populations, so they may only be applied to samples
               whose provenance is all-time.

  PEERS        fork/watcher ratios of comparable repositories
               (corpus/peers.json), bucketed by repo KIND and size. A curated
               link list is compared against other curated link lists, which is
               what stops the tool flagging them for behaving normally.

Weights, bands and thresholds are human choices and live here. Measured values
live in corpus/ and are regenerated by tools/.
"""
from __future__ import annotations

import json
from pathlib import Path

_CORPUS = Path(__file__).resolve().parent.parent / "corpus"

# ---- signal families --------------------------------------------------------
# Identity + timing, estimated from a sample of stargazers. Only scorable when
# the sample spans the repo's history (Provenance.is_all_time).
COHORT_SIGNALS: tuple[str, ...] = (
    "zero_followers_pct", "ghost_pct", "zero_repos_pct", "suspicious_pct",
    "young_median_age", "deleted_pct", "burst",
)
# Exact counts, always available, compared against type-matched peers.
STRUCTURAL_SIGNALS: tuple[str, ...] = ("fork_to_star", "watcher_to_star")

# Within a family, severities combine by weighted mean, so correlated
# fingerprints (ghost ⊆ zero_followers ∩ zero_repos) cannot multi-count.
WEIGHTS: dict[str, int] = {
    # zero_followers is the single most discriminating account fingerprint in
    # the labeled data (control 36% vs fake 70%), so it leads.
    "zero_followers_pct": 24,
    "ghost_pct": 18,
    "zero_repos_pct": 14,
    "suspicious_pct": 12,
    "young_median_age": 10,
    # Accounts that starred and have since been removed by GitHub. Real but
    # noisy — organic repos accumulate deletions too, just more slowly.
    "deleted_pct": 8,
    "burst": 14,
    # Structural family: a fork is expensive to fake, a star is not.
    "fork_to_star": 60,
    "watcher_to_star": 40,
}

# Verdict cut-points on the 0-100 scale.
BANDS: tuple[tuple[int, str], ...] = (
    (20, "LIKELY ORGANIC"),
    (49, "SUSPICIOUS"),
    (100, "LIKELY MANIPULATED"),
)
INSUFFICIENT = "INSUFFICIENT EVIDENCE"


def band_for(score: int) -> str:
    for upper, label in BANDS:
        if score <= upper:
            return label
    return BANDS[-1][1]


# ---- confidence -------------------------------------------------------------
# A cohort verdict needs both enough accounts to be stable and enough of the
# population to be representative.
MIN_ACCOUNTS = 30           # below this, cohort percentages are noise
MIN_COVERAGE = 0.05         # below this, the sample says little about the whole
HIGH_COVERAGE = 0.40
HIGH_ACCOUNTS = 100
SHRINK_PSEUDOCOUNT = 20     # empirical-Bayes pull toward the organic anchor
BURST_MIN_STARS = 50        # build-only: fewest stars for a meaningful burst ratio


def confidence_for(accounts: int, coverage: float) -> str:
    """Confidence has two independent halves, and the weaker one wins.

    PRECISION comes from how many accounts were examined. Events are lost from
    the public record by page position rather than by who starred, so a sample
    drawn from a fraction of the stars is still a fair draw — 300 accounts are
    300 accounts.

    REPRESENTATIVENESS comes from coverage, because the losses are concentrated
    in recent months. Thin coverage doesn't make the estimate noisy, it makes it
    a statement about an older slice of the repo's life.

    Recency is deliberately NOT folded in here. The archive is behind on nearly
    every actively-starred repo, so capping confidence on that basis collapsed
    the field to "medium" for everything alive and left "high" meaning little
    more than "this project is dead". It is reported on its own line instead,
    where it says something specific.
    """
    if accounts >= HIGH_ACCOUNTS:
        precision = "high"
    elif accounts >= MIN_ACCOUNTS:
        precision = "medium"
    else:
        precision = "low"

    if coverage >= HIGH_COVERAGE:
        representativeness = "high"
    elif coverage >= MIN_COVERAGE:
        representativeness = "medium"
    else:
        representativeness = "low"

    order = ("low", "medium", "high")
    return min(precision, representativeness, key=order.index)


# ---- measured anchors -------------------------------------------------------
def _load_calibration() -> dict:
    try:
        return json.loads((_CORPUS / "calibration.json").read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}


_CALIBRATION = _load_calibration()
ANCHORS: dict[str, tuple[float, float]] = {
    k: (float(v[0]), float(v[1]))
    for k, v in (_CALIBRATION.get("anchors") or {}).items()
    if not k.startswith("_") and isinstance(v, list) and len(v) == 2
}


def clamp01(x: float) -> float:
    """Severities are fractions of the way from normal to damning; nothing is
    less than normal or more than damning."""
    return max(0.0, min(1.0, x))


def anchored_severity(name: str, value: float) -> float | None:
    """Severity in [0,1] interpolated between the organic and fake anchors.

    A fake anchor BELOW the organic one (account age, fork ratio) means lower
    values are worse; the arithmetic handles both directions unchanged.
    """
    pair = ANCHORS.get(name)
    if pair is None:
        return None
    organic, fake = pair
    if fake == organic:
        return 0.0
    return clamp01((value - organic) / (fake - organic))


def shrink(name: str, value: float, n: int) -> float:
    """Pull a sampled estimate toward its organic anchor by sample size."""
    pair = ANCHORS.get(name)
    if pair is None or n <= 0:
        return value
    return (n * value + SHRINK_PSEUDOCOUNT * pair[0]) / (n + SHRINK_PSEUDOCOUNT)


# ---- repo kind --------------------------------------------------------------
# Curated lists, docs and tutorials genuinely have few forks and fewer watchers
# per star. Comparing them against software projects is the tool's oldest false
# positive, documented in its own README.
_CONTENT_TOPICS = frozenset({
    "awesome", "awesome-list", "awesome-lists", "list", "lists", "resources",
    "roadmap", "tutorial", "tutorials", "book", "books", "documentation",
    "docs", "guide", "guides", "cheatsheet", "cheatsheets", "learning",
    "course", "courses", "curated", "collection", "interview", "papers",
    "study", "notes", "education", "handbook",
})
_CONTENT_NAME_HINTS = (
    "awesome", "-list", "list-of", "roadmap", "cheatsheet", "cheat-sheet",
    "tutorial", "handbook", "guide", "notes", "papers", "book", "course",
    "curriculum", "interview", "resources", "examples", "learn",
)
_CONTENT_DESC_HINTS = (
    "curated list", "a list of", "collection of", "awesome", "resources for",
    "cheat sheet", "tutorial", "roadmap", "learning path", "study",
)
_CONTENT_LANGUAGES = frozenset({None, "Markdown", "HTML", "TeX", "CSS",
                                "Jupyter Notebook"})


def infer_kind(facts) -> str:
    """'content' for curated lists / docs / tutorials, 'code' otherwise.

    Uses only fields already present on the repo object — no extra requests.
    """
    name = facts.full_name.split("/")[-1].lower()
    topics = {t.lower() for t in (facts.topics or ())}
    desc = (facts.description or "").lower()

    if topics & _CONTENT_TOPICS:
        return "content"
    if any(h in name for h in _CONTENT_NAME_HINTS):
        return "content"
    if any(h in desc for h in _CONTENT_DESC_HINTS):
        return "content"
    # A repo with no real programming language is documentation or a list. Kept
    # last so a genuine Markdown-heavy tool isn't misfiled on language alone.
    if facts.language in _CONTENT_LANGUAGES and not topics:
        return "content"
    return "code"


# ---- peer ratios ------------------------------------------------------------
SIZE_BANDS: tuple[tuple[int, str], ...] = (
    (1_000, "0-1k"),
    (10_000, "1k-10k"),
    (50_000, "10k-50k"),
    (200_000, "50k-200k"),
    (10 ** 12, "200k+"),
)


def size_band(stars: int) -> str:
    for upper, label in SIZE_BANDS:
        if stars < upper:
            return label
    return SIZE_BANDS[-1][1]


def _load_recent() -> dict:
    try:
        return json.loads(
            (_CORPUS / "recent_baseline.json").read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}


RECENT_BASELINE = _load_recent()
MIN_RECENT_PEERS = 4

# Cohort signals a recent-window sample can support, all "higher is worse".
# Burst is excluded: a few hundred events spanning hours say nothing about a
# busiest month. deleted_pct is excluded because an account that starred
# yesterday has had no time to be removed. young_median_age is excluded until
# the baseline records a low percentile — it is the one signal where *lower* is
# worse, and a p90 ceiling would condemn nine peers in ten.
RECENT_SIGNALS: tuple[str, ...] = (
    "zero_followers_pct", "ghost_pct", "zero_repos_pct", "suspicious_pct",
)


def recent_reference(kind: str, stars: int, signal: str) -> tuple[float, float, int] | None:
    """(normal-ceiling, fake anchor, peers) for a recent-window measurement.

    The normal line is the peer cell's p90, not its median: with only a handful
    of peers per cell and wide spread — legitimate awesome-lists run anywhere
    from 40% to 82% zero-followers in their recent window — anything tighter
    would flag ordinary repos. A value only counts against a repo once it
    exceeds what every normal peer reaches.

    The fake end reuses the separation measured on all-time cohorts. The base
    rate for recent stargazers is higher than for a repo's lifetime, but the
    ratio between a bought cohort and an organic one is a property of the
    buying, so it transfers where the absolute number does not.
    """
    cells = RECENT_BASELINE.get("cells") or {}
    band = size_band(stars)
    for key in (f"{kind}|{band}", f"{kind}|*"):
        cell = cells.get(key)
        if not cell or int(cell.get("n_repos") or 0) < MIN_RECENT_PEERS:
            continue
        entry = cell.get(signal) or {}
        ceiling = entry.get("p90")
        if ceiling is None:
            continue
        pair = ANCHORS.get(signal)
        if not pair or not pair[0]:
            continue
        organic, fake = pair
        separation = (fake / organic) if organic else 1.0
        far = min(ceiling * separation, 1.0)
        if far <= ceiling:
            continue  # the ceiling already sits at saturation; nothing to scale
        return float(ceiling), float(far), int(cell.get("n_repos") or 0)
    return None


def _load_peers() -> dict:
    try:
        return json.loads((_CORPUS / "peers.json").read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}


PEERS = _load_peers()


MIN_PEERS = 12  # below this a cell's percentiles are an accident, not a reference


def peer_reference(kind: str, stars: int, signal: str) -> tuple[float, int] | None:
    """(organic reference value, peers behind it) for a ratio signal.

    The reference is the cohort's 10th percentile: a tenth of legitimate peers
    sit below it, so falling under it is unusual but not yet damning. A size
    cell with too few peers falls back to the whole kind, which is a weaker but
    honest comparison; with no peer data at all we fall back to the global
    control ratios from the calibration corpus.
    """
    cells = PEERS.get("cells") or {}
    band = size_band(stars)
    for key in (f"{kind}|{band}", f"{kind}|*"):
        cell = cells.get(key)
        if not cell or int(cell.get("n") or 0) < MIN_PEERS:
            continue
        p10 = (cell.get(signal) or {}).get("p10")
        if p10 is None:
            continue
        return float(p10), int(cell.get("n") or 0)
    # No peer table: the un-conditioned control-repo p10 from StarScout.
    pair = ANCHORS.get(signal)
    return (pair[0], 0) if pair else None
