"""Build corpus/peers.json: what fork and watcher ratios look like for ordinary
repositories, bucketed by repo KIND and size band.

Why this exists: comparing a curated link list against software projects is the
tool's oldest false positive. A per-kind, per-size reference makes "unusually
few forks for something this popular" mean something.

Sampling: GitHub code search over each star band, paginated to spread the draw
across the band rather than skimming its top, plus a content-targeted pass so
the 'content' cells aren't starved. Each candidate is then fetched individually
because search results omit subscribers_count (the real watcher count).

Usage:  python tools/build_peers.py [--per-band N] [--out PATH]
Needs a token: $GITHUB_TOKEN / $GH_TOKEN, or an authenticated `gh`.
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from _shared import bands, dedupe, percentiles, search, spread  # noqa: E402
from fakestar.baselines import infer_kind  # noqa: E402
from fakestar.evidence import RepoFacts  # noqa: E402
from fakestar.sources.github import GitHubSource, RateLimited  # noqa: E402
from fakestar.token import resolve_token  # noqa: E402


def collect(src: GitHubSource, per_band: int) -> dict[str, list[RepoFacts]]:
    buckets: dict[str, list[RepoFacts]] = {}
    for label, low, high in bands():
        print(f"band {label} ({low}..{high})", file=sys.stderr)
        candidates = dedupe(
            search(src, f"stars:{low}..{high}+sort:stars", pages=5)
            # content repos are a minority of any general draw; top them up
            + search(src, f"stars:{low}..{high}+topic:awesome", pages=2)
            + search(src, f"stars:{low}..{high}+topic:tutorial", pages=1))

        for it in spread(candidates, per_band):
            owner, _, name = it["full_name"].partition("/")
            try:
                facts = src.repo_facts(owner, name)
            except RateLimited:
                raise
            except Exception:
                continue
            if facts.stars < 200:
                continue
            key = f"{infer_kind(facts)}|{label}"
            buckets.setdefault(key, []).append(facts)
            print(f"  {facts.full_name:<50} {key:<18} "
                  f"fork/1k={1000 * facts.fork_ratio:6.0f} "
                  f"watch/1k={1000 * facts.watcher_ratio:5.0f}", file=sys.stderr)
    return buckets


def summarize(buckets: dict[str, list[RepoFacts]]) -> dict:
    cells: dict[str, dict] = {}
    for key, facts in buckets.items():
        cells[key] = {
            "n": len(facts),
            "fork_to_star": percentiles([f.fork_ratio for f in facts]),
            "watcher_to_star": percentiles([f.watcher_ratio for f in facts]),
        }
    # Kind-wide fallbacks for repos landing in a thin or missing size cell.
    for kind in ("code", "content"):
        pooled = [f for key, fs in buckets.items() if key.startswith(f"{kind}|")
                  for f in fs]
        if pooled:
            cells[f"{kind}|*"] = {
                "n": len(pooled),
                "fork_to_star": percentiles([f.fork_ratio for f in pooled]),
                "watcher_to_star": percentiles([f.watcher_ratio for f in pooled]),
            }
    return cells


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--per-band", type=int, default=60)
    ap.add_argument("--out", default=str(ROOT / "corpus" / "peers.json"))
    args = ap.parse_args(argv)

    token = resolve_token(None)
    if not token:
        print("ERROR: a GitHub token is required", file=sys.stderr)
        return 3
    src = GitHubSource(token=token, wait=True)

    buckets = collect(src, args.per_band)
    payload = {
        "_doc": "GENERATED by tools/build_peers.py. Ordinary-repo fork/watcher "
                "ratios by kind and size band; the reference a repo is judged "
                "against. Do not hand-edit.",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "method": "GitHub search per star band (paginated draw) + content "
                  "top-up; per-repo fetch for subscribers_count; repos with "
                  "published manipulation labels excluded",
        "cells": summarize(buckets),
    }
    Path(args.out).write_text(json.dumps(payload, indent=2), encoding="utf-8")
    print(f"\nwrote {args.out}")
    for key in sorted(payload["cells"]):
        cell = payload["cells"][key]
        f, w = cell["fork_to_star"], cell["watcher_to_star"]
        print(f"  {key:<20} n={cell['n']:<4} fork/1k p10={1000*f.get('p10',0):6.0f} "
              f"p25={1000*f.get('p25',0):6.0f} p50={1000*f.get('p50',0):6.0f}  "
              f"watch/1k p25={1000*w.get('p25',0):5.0f}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
